<?xml version="1.0" encoding="utf-8" ?>
<Project>
    <PropertyGroup>
        <!-- This points to where your game is located on your disk. -->
        <GamePath>C:\Program Files (x86)\Steam\steamapps\common\Gorilla Tag</GamePath>

        <GameAssemblyPath>$(GamePath)\Gorilla Tag_Data\Managed</GameAssemblyPath>
        <BepInExAssemblyPath>$(GamePath)\BepInEx\core</BepInExAssemblyPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(CI)'=='TRUE'">
        <GameAssemblyPath>$(SolutionDir)Libs</GameAssemblyPath>
        <BepInExAssemblyPath>$(SolutionDir)Libs</BepInExAssemblyPath>
    </PropertyGroup>
</Project>
