<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable> 

		<!-- Add debug symbols which are useful for debugging later. This points out line numbers of
		errors to you inside of your log file. -->
		<DebugType Condition="'$(Configuration)'=='Debug'">embedded</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<!-- Allows us to use all of the functions Gorilla Tag offers. -->
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="HarmonyLib">
			<HintPath>$(BepInExAssemblyPath)\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx">
			<HintPath>$(BepInExAssemblyPath)\BepInEx.dll</HintPath>
		</Reference>

		<Reference Include="Assembly_CSharp" Publicize="true">
			<HintPath>$(GameAssemblyPath)\Assembly_CSharp.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="$(GameAssemblyPath)\*.dll"
             Exclude="$(GameAssemblyPath)\mscorlib.dll;$(GameAssemblyPath)\System*.dll;$(GameAssemblyPath)\netstandard.dll;$(GameAssemblyPath)\Assembly_CSharp.dll">
			<HintPath>%(Identity)</HintPath>
		</Reference>
	</ItemGroup>
</Project>